version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend/transactions.json:/app/transactions.json

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped